### ISSUE TITLE
example/ge-spmm 

### ISSUE THREAD

**Issue by Liyinyue** [dgSPARSE/dgSPARSE-Lib#14]
When running example ./spmm.out ../data/p2p-Gnutella31.mtx X
if X is not a 2^n integer
it reports like Wrong result: i = 363, j = 0, result = 0.000000, reference = 0.070000. 

Only when X is a 2^n integer we can view the result correctly

**Comment by hgyhungry** [comment]
Can you provide the exact X you tested?

I tested some non power-of-2 X, but I see no errors. For example 
(base) guyue@server:~/dgSPARSE-Library/example/ge-spmm$ ./spmm.out ../data/p2p-Gnutella31.mtx 143
Finish reading matrix 62586 rows, 62586 columns, 147892 nnz. 
Ignore original values and use randomly generated values.
[Cusparse] Report: spmm A(62586 x 62586) * B(62586 x 143) sparsity 0.000038 (nnz=147892) 
 Time 0.205066 (ms), Throughput 206.260712 (gflops).
[GE-SpMM][Alg: 0] Report: spmm A(62586 x 62586) * B(62586 x 143) sparsity 0.000038 (nnz=147892) 
 Time 0.124068 (ms), Throughput 340.919220 (gflops).
[GE-SpMM][Alg: 1] Report: spmm A(62586 x 62586) * B(62586 x 143) sparsity 0.000038 (nnz=147892) 
 Time 3.161272 (ms), Throughput 13.379775 (gflops).
[GE-SpMM][Alg: 2] Report: spmm A(62586 x 62586) * B(62586 x 143) sparsity 0.000038 (nnz=147892) 
 Time 1.157284 (ms), Throughput 36.548603 (gflops).
[GE-SpMM][Alg: 3] Report: spmm A(62586 x 62586) * B(62586 x 143) sparsity 0.000038 (nnz=147892) 
 Time 1.123594 (ms), Throughput 37.644474 (gflops).
[GE-SpMM][Alg: 8] Report: spmm A(62586 x 62586) * B(62586 x 143) sparsity 0.000038 (nnz=147892) 
 Time 0.115343 (ms), Throughput 366.706085 (gflops).
[GE-SpMM][Alg: 9] Report: spmm A(62586 x 62586) * B(62586 x 143) sparsity 0.000038 (nnz=147892) 
 Time 0.093368 (ms), Throughput 453.013519 (gflops).

**Comment by MathsCode** [comment]
We have solved the problem. Please re-download the code.
The previous code may cause the access out of bounds problem. So we add a bounf check.

**Comment by MathsCode** [comment]
We have solved the problem. Please re-download the code.
The previous code may cause the access out of bounds problem. So we add a simple bound check.
